plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: "cargo release --skip-tags true --no-dev-version true --no-confirm ${nextRelease.version}"
      publishCmd: "publish-package"
