[package]
name = "slack-blocks"
version = "0.1.0"
description = "Data structure definitions for Slack's Block Kit API - With client-side validation and helper macros"

edition = "2018"
authors = ["Orion Kindel <cakekindel@gmail.com>"]
license = "MIT OR Apache-2.0"

homepage = "https://github.com/cakekindel/slack-block-kit-rs"
repository = "https://github.com/cakekindel/slack-block-kit-rs"
readme = "README.md"

keywords = ["slack", "model", "models", "validation", "json"]
categories = ["data-structures"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "1.0.18"
validator = "0.10.0"
validator_derive = "0.10.0"
lazy_static = "1.4.0"
derive_builder = "0.9.0"

[dev-dependencies]
test-case = "1.0.0"

