[package]
name = "slack-block-kit"
description = "Data structure definitions for Slack's Block Kit API - With client-side validation and macros for static messages"
version = "0.1.0"
authors = ["Orion Kindel <cakekindel@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["model", "models", "validation", "slack", "block kit"]
categories = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "1.0.18"
validator = "0.10.0"
validator_derive = "0.10.0"

[dev-dependencies]
test-case = "1.0.0"

