[package]
name = "slack-block-kit"
version = "0.1.0"
authors = ["Orion Kindel <cakekindel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "1.0.18"

[dev-dependencies]
test-case = "1.0.0"

