[env]
RUST_BACKTRACE = "1"

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]

[tasks.doctest]
command = "cargo"
args = ["--locked", "test", "--doc", "--", "--quiet"]

[tasks.test]
command = "cargo"
args = ["--locked", "test", "--tests", "--", "--quiet"]
dependencies = ["doctest"]

[tasks.tdd]
install_crate = "cargo-watch"
command = "cargo"
args = [ "watch"
       , "--watch", "./src"
       , "--watch", "./tests"
       , "--delay", "0"
       , "-x", "make -t test"
       ]

[tasks.check-fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.check-clippy]
command = "cargo"
args = ["clippy"]

[tasks.ci]
dependencies = ["test", "check-fmt", "check-clippy"]

[tasks.update-readme]
script = "cargo install cargo-readme && cargo readme > README.md"
