name: 'bump'

on:
  push:
    branches: [ 'master' ]

jobs:
  bump:
    if: "!contains(github.event.head_commit.message, 'bump') && !contains(github.event.head_commit.message, 'ci')"
    runs-on: 'ubuntu-latest'
    steps:

    # Setup
    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - uses: 'actions/checkout@v2'

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    # update version,
    #   gen/update CHANGELOG,
    #   gen version tag
    - run: 'npx standard-version'

    # make sure build passes +
    #   update version in Cargo.lock
    #   so CI caches still work
    - name: 'ensure Cargo.lock fresh'
      run: 'cargo c'

    # Open PR for manifest changes
    - name: 'create pull request'
      uses: 'peter-evans/create-pull-request@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: regen Cargo.lock
        title: 'bump: new version'

    # Push the new tag, triggering a publish
    - name: 'push tags'
      run: 'git push --tags'

