name: 'bump'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore(release)')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:

    # Setup
    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    # run `standard-version`
    # - update CHANGELOG,
    # - create version tag
    # - create version commits
    - run: 'npx standard-version'

    - name: 'Update our own version in Cargo.lock'
      run: 'cargo c'

    - name: 'push changes to main'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push'

    # triggers 'publish' job
    - name: 'push tags'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: 'git push --tags'
