name: 'ci check'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  ci_check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: 'actions/checkout@v2'
    - run: 'cargo build'
    - run: 'cargo test'
