name: 'ci check'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  ci_check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - run: 'ls -A ~/.cargo'
    - run: 'ls -A ~/.cargo/bin'

    - run: '[ ! -f ~/.cargo/bin/cargo-make ] && cargo install cargo-make'
    - run: 'cargo make ci'
