name: 'publish'

on: tags

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'actions/cache@v2'
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: 'Publish'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
