name: 'publish'

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    # Setup
    - uses: 'actions/checkout@v2'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Push changes to crates.io
    - name: 'Publish'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: 'cargo publish'
